#!/bin/bash
bashdir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ -d $bashdir/shell ]; then
    echo -e "Found sender. Skipping download"
else
    wget -t 5 -O Zapretyan.tar.gz 'https://github.com/SHULKERPLAY/Zapretyan-Lite/releases/download/1/zapretyan.tar.gz' && tar -xf Zapretyan.tar.gz && rm Zapretyan.tar.gz
fi

echo -e "Found $bashdir"
echo Script uses relative paths - Checking files
if [ -e $bashdir/shell/zapretyanlite.sh ]; then
    echo Found shell files
else
    echo -e "ERROR. CANNOT FIND $bashdir/shell/zapretyanlite.sh . Aborting..."
    exit 1
fi
echo Check complete
sleep 1

echo Enter absolute path where zapretyan lite will be and we prepare all for you
echo If you want to change path to dir in the future, you will need to change them in config.cfg
echo e.g. /root/zapretyan
read -r installpath

mkdir $installpath
if [ -d $installpath ]; then
    echo -e "Directory Created ($installpath)"
else
    echo -e "ERROR. CANNOT FIND $installpath . Do i have access to directory or my path is wrong?"
    exit 1
fi
sleep 1

while true; do
    echo Zapretyan requires git, curl
    read -r -p "Do you want to install dependencies? Y/N" yn
    case $yn in
        [Yy]* ) apt update && apt install git curl -y; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
sleep 1

echo Installing Zapretyan in 5 seconds...
sleep 5

echo Moving shell to install path...
mv shell $installpath
echo Changing dir to install path...
cd $installpath

echo recheck files
if [ -e $installpath/shell/zapretyanlite.sh ]; then
    echo Found shell files
else
    echo -e "ERROR. CANNOT FIND $installpath/shell/zapretyanlite.sh . Aborting..."
    exit 1
fi

echo Modifying config.cfg...
echo -e "#AUTOCONFIG. REMOVE LINES BELOW TO EDIT SAME VARIABLES ABOVE" >> shell/config.cfg
echo -e "shdir=$installpath/shell" >> shell/config.cfg

while true; do
    read -r -p "Do you want to install system timer for Zapretyan? Y/N" yn
    case $yn in
        [Yy]* ) build=true; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
if [ "$build" = true ]; then
    echo Building service
    echo -e "#AUTOGENERATED BY INSTALLER" > zapretyan.service
    echo -e "[Unit]\nDescription=Zapretyan - Russia internet bans notifier. https://github.com/SHULKERPLAY/Zapretyan-Lite/\n" >> zapretyan.service
    echo -e "[Service]\nExecStart=/bin/bash $installpath/shell/zapretyanlite.sh\n" >> zapretyan.service

    echo Building timer
    echo -e "#AUTOGENERATED BY INSTALLER" > zapretyan.timer
    echo -e "[Unit]\nDescription=Trigger for Zapretyan - Russia internet bans notifier\n" >> zapretyan.timer
    echo -e "[Timer]\nPersistent=true\nOnCalendar=Mon..Sun *-*-* 08:00:00\n" >> zapretyan.timer
    echo -e "[Install]\nWantedBy=timers.target" >> zapretyan.timer

    echo Installing timer
    mv zapretyan.service /etc/systemd/system
    mv zapretyan.timer /etc/systemd/system
    echo Enabling timer
    systemctl enable zapretyan.timer
    systemctl start zapretyan.timer
else
    echo Skipping...
fi

echo -e "\n\n\nDone!\nEdit /etc/systemd/system/zapretyan.timer if you want to change time when checks are starting (Default: 8 AM).\nType 'systemctl status zapretyan.timer' to check if installation complete.\nsystemctl disable zapretyan.timer to stop service."
echo -e "Now you need to edit $installpath/shell/config.cfg to enable notifications and setup your Discord Webhooks"